# Generated by Django 2.1.2 on 2018-11-24 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0006_review_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('comment_date', models.DateTimeField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djbg.Review')),
            ],
        ),
    ]
