# Generated by Django 2.1.2 on 2018-11-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
