# Generated by Django 2.1.2 on 2018-11-24 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0011_auto_20181124_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='djbg.Creator'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(related_name='games', to='djbg.Tag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='games', to='djbg.Game'),
        ),
    ]
