# Generated by Django 2.1.2 on 2018-11-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0013_auto_20181124_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='game',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='user',
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='static'),
        ),
    ]
