# Generated by Django 2.1.2 on 2018-12-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0016_picture_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='games',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
