# Generated by Django 2.1.2 on 2018-12-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0018_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
    ]
