# Generated by Django 2.1.2 on 2018-12-25 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0019_remove_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='djbg.Profile'),
            preserve_default=False,
        ),
    ]
