# Generated by Django 2.1.2 on 2019-02-18 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0020_comment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='profile',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='djbg.Profile'),
        ),
    ]
