# Generated by Django 2.1.2 on 2019-02-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0021_review_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='profile',
        ),
    ]
