# Generated by Django 2.1.2 on 2019-02-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0024_remove_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.TextField(default='Argyro'),
        ),
    ]
