# Generated by Django 2.1.2 on 2019-02-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0025_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
    ]
