# Generated by Django 2.1.2 on 2019-02-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0026_remove_comment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.TextField(default='Argyro'),
        ),
    ]
