# Generated by Django 2.1.2 on 2019-02-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0027_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='times_rated',
            field=models.IntegerField(default=0),
        ),
    ]
