# Generated by Django 2.1.2 on 2019-02-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0028_game_times_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
