# Generated by Django 2.1.2 on 2019-02-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0029_auto_20190218_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='picture',
            field=models.ImageField(default='http://127.0.0.1:8000/api/static/game/wizard_FvHnMwM.jpg', upload_to='static/game'),
        ),
    ]
