# Generated by Django 2.1.2 on 2019-02-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0030_game_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='picture',
        ),
    ]
