# Generated by Django 2.1.2 on 2018-11-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creator', models.CharField(max_length=50)),
                ('rules', models.TextField(default='')),
                ('price', models.IntegerField(verbose_name='average price in the market')),
                ('picture', models.ImageField(upload_to='static/game')),
                ('release_date', models.DateField()),
                ('rate', models.IntegerField()),
                ('min_age', models.IntegerField(default=0)),
                ('max_age', models.IntegerField(default=100)),
            ],
        ),
    ]
