# Generated by Django 2.1.2 on 2018-11-22 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='games',
        ),
    ]
