# Generated by Django 2.1.2 on 2018-11-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0002_profile_review_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(blank=True, to='djbg.Game'),
        ),
    ]
