# Generated by Django 2.1.2 on 2018-11-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0003_game_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_num_of_players',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='game',
            name='min_num_of_players',
            field=models.IntegerField(default=1),
        ),
    ]
