# Generated by Django 2.1.2 on 2018-11-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0004_auto_20181124_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
