# Generated by Django 2.1.2 on 2018-11-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0004_auto_20181109_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='static/profile')),
                ('birth_date', models.DateField()),
                ('games', models.ManyToManyField(blank=True, to='djbg.Game')),
            ],
        ),
    ]
