# Generated by Django 2.1.2 on 2018-11-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0008_remove_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='static/profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djbg.Profile')),
            ],
        ),
    ]
