# Generated by Django 2.1.2 on 2018-11-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0010_auto_20181124_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='games',
            new_name='tags',
        ),
    ]
