# Generated by Django 2.1.2 on 2018-11-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0014_auto_20181126_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
