# Generated by Django 2.1.2 on 2018-11-26 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djbg', '0015_delete_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture_game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='static/game')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djbg.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
